### ISSUE TITLE
config.maxWorkers being checked twice on line 23 and line 27

### ISSUE THREAD

**Issue by krshubham** [softvar/super-workers#2]
Hi, 
I was just checking the code a bit and found that both these mentioned lines have checked the value of:
```javascript
if(typeof config.maxWorkers === 'undefined')
```
I think it should be ```config.minWorkers``` in line 23. 

https://github.com/softvar/super-workers/blob/4a1122076af867e69cc4ff284c96126859bb45f8/src/MainThread.js#L23
https://github.com/softvar/super-workers/blob/4a1122076af867e69cc4ff284c96126859bb45f8/src/MainThread.js#L27

**Comment by krshubham** [comment]
I don't if it was intentional, so let me know if I am wrong

**Comment by softvar** [comment]
@krshubham You're right. Thanks for noticing and telling. Will fix it soon.

**Comment by softvar** [comment]
Fixed in v1.0.1 :)
